//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookFair.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BookFair.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors with Author&apos;s Books on Wishlist.
        /// </summary>
        public static string AuthorVisitors_WindowDefaultTitle {
            get {
                return ResourceManager.GetString("AuthorVisitors_WindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors with &apos;{0}&apos; books on wishlist.
        /// </summary>
        public static string AuthorVisitors_WindowTitleFormat {
            get {
                return ResourceManager.GetString("AuthorVisitors_WindowTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string Btn_Compare {
            get {
                return ResourceManager.GetString("Btn_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected.
        /// </summary>
        public static string BtnDeleteTooltip {
            get {
                return ResourceManager.GetString("BtnDeleteTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected.
        /// </summary>
        public static string BtnEditTooltip {
            get {
                return ResourceManager.GetString("BtnEditTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string BtnNewTooltip {
            get {
                return ResourceManager.GetString("BtnNewTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BtnSearchTooltip {
            get {
                return ResourceManager.GetString("BtnSearchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Form_Address {
            get {
                return ResourceManager.GetString("Form_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Form_Author {
            get {
                return ResourceManager.GetString("Form_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string Form_City {
            get {
                return ResourceManager.GetString("Form_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string Form_Code {
            get {
                return ResourceManager.GetString("Form_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string Form_Country {
            get {
                return ResourceManager.GetString("Form_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth:.
        /// </summary>
        public static string Form_DateOfBirth {
            get {
                return ResourceManager.GetString("Form_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string Form_Email {
            get {
                return ResourceManager.GetString("Form_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string Form_Genre {
            get {
                return ResourceManager.GetString("Form_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card Number:.
        /// </summary>
        public static string Form_IDCardNumber {
            get {
                return ResourceManager.GetString("Form_IDCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN:.
        /// </summary>
        public static string Form_ISBN {
            get {
                return ResourceManager.GetString("Form_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Card Number:.
        /// </summary>
        public static string Form_MembershipCardNumber {
            get {
                return ResourceManager.GetString("Form_MembershipCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Form_Name {
            get {
                return ResourceManager.GetString("Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string Form_Number {
            get {
                return ResourceManager.GetString("Form_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pages:.
        /// </summary>
        public static string Form_NumberOfPages {
            get {
                return ResourceManager.GetString("Form_NumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Form_Phone {
            get {
                return ResourceManager.GetString("Form_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price:.
        /// </summary>
        public static string Form_Price {
            get {
                return ResourceManager.GetString("Form_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Form_Status {
            get {
                return ResourceManager.GetString("Form_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string Form_Street {
            get {
                return ResourceManager.GetString("Form_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string Form_Surname {
            get {
                return ResourceManager.GetString("Form_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of Release:.
        /// </summary>
        public static string Form_YearOfRelease {
            get {
                return ResourceManager.GetString("Form_YearOfRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience:.
        /// </summary>
        public static string Form_YearsOfExperience {
            get {
                return ResourceManager.GetString("Form_YearsOfExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book.
        /// </summary>
        public static string FormBtn_AddBook {
            get {
                return ResourceManager.GetString("FormBtn_AddBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormBtn_Cancel {
            get {
                return ResourceManager.GetString("FormBtn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Purchase.
        /// </summary>
        public static string FormBtn_CancelPurchase {
            get {
                return ResourceManager.GetString("FormBtn_CancelPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string FormBtn_Confirm {
            get {
                return ResourceManager.GetString("FormBtn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string FormBtn_ConfirmRemoveAuthor {
            get {
                return ResourceManager.GetString("FormBtn_ConfirmRemoveAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string FormBtn_ConfirmSelection {
            get {
                return ResourceManager.GetString("FormBtn_ConfirmSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FormBtn_Delete {
            get {
                return ResourceManager.GetString("FormBtn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string FormBtn_Purchase {
            get {
                return ResourceManager.GetString("FormBtn_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Book.
        /// </summary>
        public static string FormBtn_RemoveBook {
            get {
                return ResourceManager.GetString("FormBtn_RemoveBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FormBtn_Save {
            get {
                return ResourceManager.GetString("FormBtn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Authors.
        /// </summary>
        public static string FormBtn_ShowAuthors {
            get {
                return ResourceManager.GetString("FormBtn_ShowAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Visitors.
        /// </summary>
        public static string FormBtn_ShowVisitors {
            get {
                return ResourceManager.GetString("FormBtn_ShowVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string FormGrid_Author {
            get {
                return ResourceManager.GetString("FormGrid_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying date.
        /// </summary>
        public static string FormGrid_BuyingDate {
            get {
                return ResourceManager.GetString("FormGrid_BuyingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FormGrid_Date {
            get {
                return ResourceManager.GetString("FormGrid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string FormGrid_Publisher {
            get {
                return ResourceManager.GetString("FormGrid_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string FormGrid_Rating {
            get {
                return ResourceManager.GetString("FormGrid_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string FormTab_Information {
            get {
                return ResourceManager.GetString("FormTab_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchased.
        /// </summary>
        public static string FormTab_Purchased {
            get {
                return ResourceManager.GetString("FormTab_Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist.
        /// </summary>
        public static string FormTab_Wishlist {
            get {
                return ResourceManager.GetString("FormTab_Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Book to Wishlist.
        /// </summary>
        public static string FormTitle_AddWishlistBook {
            get {
                return ResourceManager.GetString("FormTitle_AddWishlistBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose author.
        /// </summary>
        public static string FormTitle_ChooseAuthor {
            get {
                return ResourceManager.GetString("FormTitle_ChooseAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Publisher.
        /// </summary>
        public static string FormTitle_EditPublisher {
            get {
                return ResourceManager.GetString("FormTitle_EditPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Author.
        /// </summary>
        public static string FormTitle_NewAuthor {
            get {
                return ResourceManager.GetString("FormTitle_NewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Book.
        /// </summary>
        public static string FormTitle_NewBook {
            get {
                return ResourceManager.GetString("FormTitle_NewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Publisher.
        /// </summary>
        public static string FormTitle_NewPublisher {
            get {
                return ResourceManager.GetString("FormTitle_NewPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Visitor.
        /// </summary>
        public static string FormTitle_NewVisitor {
            get {
                return ResourceManager.GetString("FormTitle_NewVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase book.
        /// </summary>
        public static string FormTitle_PurchaseBook {
            get {
                return ResourceManager.GetString("FormTitle_PurchaseBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove author.
        /// </summary>
        public static string FormTitle_RemoveAuthorConfirm {
            get {
                return ResourceManager.GetString("FormTitle_RemoveAuthorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Author.
        /// </summary>
        public static string FormTitle_UpdateAuthor {
            get {
                return ResourceManager.GetString("FormTitle_UpdateAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Book.
        /// </summary>
        public static string FormTitle_UpdateBook {
            get {
                return ResourceManager.GetString("FormTitle_UpdateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Visitor.
        /// </summary>
        public static string FormTitle_UpdateVisitor {
            get {
                return ResourceManager.GetString("FormTitle_UpdateVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adventure.
        /// </summary>
        public static string Genre_Avantura {
            get {
                return ResourceManager.GetString("Genre_Avantura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Genre_Biografija {
            get {
                return ResourceManager.GetString("Genre_Biografija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string Genre_Drama {
            get {
                return ResourceManager.GetString("Genre_Drama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiction.
        /// </summary>
        public static string Genre_Fikcija {
            get {
                return ResourceManager.GetString("Genre_Fikcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Genre_Istorija {
            get {
                return ResourceManager.GetString("Genre_Istorija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crime.
        /// </summary>
        public static string Genre_Kriminalistika {
            get {
                return ResourceManager.GetString("Genre_Kriminalistika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Fiction.
        /// </summary>
        public static string Genre_NaucnaFantastika {
            get {
                return ResourceManager.GetString("Genre_NaucnaFantastika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry.
        /// </summary>
        public static string Genre_Poezija {
            get {
                return ResourceManager.GetString("Genre_Poezija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel.
        /// </summary>
        public static string Genre_Roman {
            get {
                return ResourceManager.GetString("Genre_Roman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romance.
        /// </summary>
        public static string Genre_Romantika {
            get {
                return ResourceManager.GetString("Genre_Romantika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        public static string Genre_Triler {
            get {
                return ResourceManager.GetString("Genre_Triler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string GridAuthors_DateOfBirth {
            get {
                return ResourceManager.GetString("GridAuthors_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string GridAuthors_Email {
            get {
                return ResourceManager.GetString("GridAuthors_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Card Number.
        /// </summary>
        public static string GridAuthors_IdCardNumber {
            get {
                return ResourceManager.GetString("GridAuthors_IdCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GridAuthors_Name {
            get {
                return ResourceManager.GetString("GridAuthors_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string GridAuthors_Surname {
            get {
                return ResourceManager.GetString("GridAuthors_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GridBooks_Genre {
            get {
                return ResourceManager.GetString("GridBooks_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string GridBooks_ISBN {
            get {
                return ResourceManager.GetString("GridBooks_ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GridBooks_Name {
            get {
                return ResourceManager.GetString("GridBooks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string GridBooks_Price {
            get {
                return ResourceManager.GetString("GridBooks_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Of Release.
        /// </summary>
        public static string GridBooks_YearOfRelease {
            get {
                return ResourceManager.GetString("GridBooks_YearOfRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string GridPublishers {
            get {
                return ResourceManager.GetString("GridPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string GridPublishers_Code {
            get {
                return ResourceManager.GetString("GridPublishers_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head ID.
        /// </summary>
        public static string GridPublishers_HeadId {
            get {
                return ResourceManager.GetString("GridPublishers_HeadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string GridPublishers_ID {
            get {
                return ResourceManager.GetString("GridPublishers_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string GridVisitors_Address {
            get {
                return ResourceManager.GetString("GridVisitors_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string GridVisitors_MembershipCardNumber {
            get {
                return ResourceManager.GetString("GridVisitors_MembershipCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GridVisitors_Name {
            get {
                return ResourceManager.GetString("GridVisitors_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string GridVisitors_Status {
            get {
                return ResourceManager.GetString("GridVisitors_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string GridVisitors_Surname {
            get {
                return ResourceManager.GetString("GridVisitors_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book 1:.
        /// </summary>
        public static string Label_Book1 {
            get {
                return ResourceManager.GetString("Label_Book1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book 2:.
        /// </summary>
        public static string Label_Book2 {
            get {
                return ResourceManager.GetString("Label_Book2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Fair.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string MenuClose {
            get {
                return ResourceManager.GetString("MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Visitors by Books.
        /// </summary>
        public static string MenuCompareVisitors {
            get {
                return ResourceManager.GetString("MenuCompareVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MenuEditDelete {
            get {
                return ResourceManager.GetString("MenuEditDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MenuEditModify {
            get {
                return ResourceManager.GetString("MenuEditModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MenuEnglish {
            get {
                return ResourceManager.GetString("MenuEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuHelpAbout {
            get {
                return ResourceManager.GetString("MenuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string MenuOpenAuthors {
            get {
                return ResourceManager.GetString("MenuOpenAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string MenuOpenBooks {
            get {
                return ResourceManager.GetString("MenuOpenBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string MenuOpenPublishers {
            get {
                return ResourceManager.GetString("MenuOpenPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string MenuOpenVisitors {
            get {
                return ResourceManager.GetString("MenuOpenVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher authors.
        /// </summary>
        public static string MenuPublisherAuthors {
            get {
                return ResourceManager.GetString("MenuPublisherAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Books by Publisher.
        /// </summary>
        public static string MenuPublisherBooks {
            get {
                return ResourceManager.GetString("MenuPublisherBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string MenuSerbian {
            get {
                return ResourceManager.GetString("MenuSerbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Publisher Head.
        /// </summary>
        public static string MenuSetPublisherHead {
            get {
                return ResourceManager.GetString("MenuSetPublisherHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author must have at least 5 years of experience. Selected author has {0} years..
        /// </summary>
        public static string Msg_AuthorExperienceError {
            get {
                return ResourceManager.GetString("Msg_AuthorExperienceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buying date is required..
        /// </summary>
        public static string Msg_BuyingDateRequired {
            get {
                return ResourceManager.GetString("Msg_BuyingDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the purchase?.
        /// </summary>
        public static string Msg_ConfirmCancelPurchase {
            get {
                return ResourceManager.GetString("Msg_ConfirmCancelPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Msg_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {0} book(s) from the author?.
        /// </summary>
        public static string Msg_ConfirmRemoveAuthorBooks {
            get {
                return ResourceManager.GetString("Msg_ConfirmRemoveAuthorBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Msg_ErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Msg_InfoTitle {
            get {
                return ResourceManager.GetString("Msg_InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available books to add..
        /// </summary>
        public static string Msg_NoAvailableBooksToAdd {
            get {
                return ResourceManager.GetString("Msg_NoAvailableBooksToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available books for adding (all have been purchased or are already on the wishlist)..
        /// </summary>
        public static string Msg_NoAvailableWishlistBooks {
            get {
                return ResourceManager.GetString("Msg_NoAvailableWishlistBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found for this author..
        /// </summary>
        public static string Msg_NoBooksAuthor {
            get {
                return ResourceManager.GetString("Msg_NoBooksAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author &apos;{0}&apos; has been set as head of &apos;{1}&apos;..
        /// </summary>
        public static string Msg_PublisherHeadSetSuccess {
            get {
                return ResourceManager.GetString("Msg_PublisherHeadSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating must be between 1 and 5..
        /// </summary>
        public static string Msg_RatingRange {
            get {
                return ResourceManager.GetString("Msg_RatingRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the author?.
        /// </summary>
        public static string Msg_RemoveAuthorConfirm {
            get {
                return ResourceManager.GetString("Msg_RemoveAuthorConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Msg_SavedTitle {
            get {
                return ResourceManager.GetString("Msg_SavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an author first..
        /// </summary>
        public static string Msg_SelectAuthor {
            get {
                return ResourceManager.GetString("Msg_SelectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an author from the dropdown..
        /// </summary>
        public static string Msg_SelectAuthorDropdown {
            get {
                return ResourceManager.GetString("Msg_SelectAuthorDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an author..
        /// </summary>
        public static string Msg_SelectAuthorHeads {
            get {
                return ResourceManager.GetString("Msg_SelectAuthorHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a book first..
        /// </summary>
        public static string Msg_SelectBook {
            get {
                return ResourceManager.GetString("Msg_SelectBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one book from the list..
        /// </summary>
        public static string Msg_SelectBookFromList {
            get {
                return ResourceManager.GetString("Msg_SelectBookFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one book in the table..
        /// </summary>
        public static string Msg_SelectBookInTable {
            get {
                return ResourceManager.GetString("Msg_SelectBookInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select both books..
        /// </summary>
        public static string Msg_SelectBothBooks {
            get {
                return ResourceManager.GetString("Msg_SelectBothBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select two different books..
        /// </summary>
        public static string Msg_SelectDifferentBooks {
            get {
                return ResourceManager.GetString("Msg_SelectDifferentBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a publisher first..
        /// </summary>
        public static string Msg_SelectPublisher {
            get {
                return ResourceManager.GetString("Msg_SelectPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a publisher..
        /// </summary>
        public static string Msg_SelectPublisherHeads {
            get {
                return ResourceManager.GetString("Msg_SelectPublisherHeads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a purchase in the table..
        /// </summary>
        public static string Msg_SelectPurchase {
            get {
                return ResourceManager.GetString("Msg_SelectPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a visitor first..
        /// </summary>
        public static string Msg_SelectVisitor {
            get {
                return ResourceManager.GetString("Msg_SelectVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current state is saved..
        /// </summary>
        public static string Msg_StateSaved {
            get {
                return ResourceManager.GetString("Msg_StateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Msg_SuccessTitle {
            get {
                return ResourceManager.GetString("Msg_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string Msg_ValidationErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string Msg_ValidationTitle {
            get {
                return ResourceManager.GetString("Msg_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor not found..
        /// </summary>
        public static string Msg_VisitorNotFound {
            get {
                return ResourceManager.GetString("Msg_VisitorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor has no books on wishlist..
        /// </summary>
        public static string Msg_VisitorNoWishlist {
            get {
                return ResourceManager.GetString("Msg_VisitorNoWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} books from the wishlist?.
        /// </summary>
        public static string Msg_WishlistConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_WishlistConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to purchase {0} book(s)?.
        /// </summary>
        public static string Msg_WishlistConfirmPurchase {
            get {
                return ResourceManager.GetString("Msg_WishlistConfirmPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Purchase.
        /// </summary>
        public static string Msg_WishlistConfirmTitle {
            get {
                return ResourceManager.GetString("Msg_WishlistConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one book in the table..
        /// </summary>
        public static string Msg_WishlistSelectBook {
            get {
                return ResourceManager.GetString("Msg_WishlistSelectBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher authors: {0}.
        /// </summary>
        public static string PublisherAuthors_WindowTitleFormat {
            get {
                return ResourceManager.GetString("PublisherAuthors_WindowTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found for publisher &apos;{0}&apos;..
        /// </summary>
        public static string PublisherBooks_NoBooksMessage {
            get {
                return ResourceManager.GetString("PublisherBooks_NoBooksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string PublisherBooks_SearchLabel {
            get {
                return ResourceManager.GetString("PublisherBooks_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books by Publisher.
        /// </summary>
        public static string PublisherBooks_WindowDefaultTitle {
            get {
                return ResourceManager.GetString("PublisherBooks_WindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books from &apos;{0}&apos;.
        /// </summary>
        public static string PublisherBooks_WindowTitle {
            get {
                return ResourceManager.GetString("PublisherBooks_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Head.
        /// </summary>
        public static string PublisherHeads_BtnSetHead {
            get {
                return ResourceManager.GetString("PublisherHeads_BtnSetHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors (MinExp: 5 years).
        /// </summary>
        public static string PublisherHeads_LabelAuthors {
            get {
                return ResourceManager.GetString("PublisherHeads_LabelAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string PublisherHeads_LabelPublishers {
            get {
                return ResourceManager.GetString("PublisherHeads_LabelPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Publisher Head.
        /// </summary>
        public static string PublisherHeads_WindowTitle {
            get {
                return ResourceManager.GetString("PublisherHeads_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Publishers_Name {
            get {
                return ResourceManager.GetString("Publishers_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchBoxTooltip {
            get {
                return ResourceManager.GetString("SearchBoxTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating: {0:0.0}.
        /// </summary>
        public static string Stat_AverageRating {
            get {
                return ResourceManager.GetString("Stat_AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent: {0:0} RSD.
        /// </summary>
        public static string Stat_TotalSpent {
            get {
                return ResourceManager.GetString("Stat_TotalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string StatusBar_Date {
            get {
                return ResourceManager.GetString("StatusBar_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Fair Application.
        /// </summary>
        public static string StatusBar_Main {
            get {
                return ResourceManager.GetString("StatusBar_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string StatusBar_Time {
            get {
                return ResourceManager.GetString("StatusBar_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bought first only.
        /// </summary>
        public static string Tab_BoughtFirstOnly {
            get {
                return ResourceManager.GetString("Tab_BoughtFirstOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wishlist both.
        /// </summary>
        public static string Tab_WishlistBoth {
            get {
                return ResourceManager.GetString("Tab_WishlistBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string TabAuthors {
            get {
                return ResourceManager.GetString("TabAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string TabBooks {
            get {
                return ResourceManager.GetString("TabBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishers.
        /// </summary>
        public static string TabPublishers {
            get {
                return ResourceManager.GetString("TabPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string TabVisitors {
            get {
                return ResourceManager.GetString("TabVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors from Visitor Wishlist.
        /// </summary>
        public static string VisitorAuthors_WindowDefaultTitle {
            get {
                return ResourceManager.GetString("VisitorAuthors_WindowDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors for visitor &apos;{0}&apos;.
        /// </summary>
        public static string VisitorAuthors_WindowTitleFormat {
            get {
                return ResourceManager.GetString("VisitorAuthors_WindowTitleFormat", resourceCulture);
            }
        }
    }
}
